[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std = "1.11.0"
entity = { path = "../entity" }

[dependencies.sea-orm-migration]
version = "^0.8.0"
features = ["runtime-tokio-native-tls", "sqlx-sqlite"]

[dependencies.sea-orm]
version = "^0.8.0"
features = ["runtime-tokio-native-tls", "sqlx-sqlite", "with-chrono"]
