//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::post_tags::Entity as PostTags;
pub use super::posts::Entity as Posts;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::tags::Entity as Tags;
pub use super::uploads::Entity as Uploads;
pub use super::users::Entity as Users;
